### PR TITLE
Shortcircuit sync loop if we've requested to stop syncing

### LINKED ISSUE #322: Don't backoff sync if stop has been called on Client.
During test runs it's fairly common to run a sync loop, then end the sync loop and immediately kill the homeserver. This typically causes an exception to be thrown as the Client will be listening for a response, and will then backoff that error.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #322 

Signed off by Will Hunt <me@half-shot.uk>

## Checklist

* [ ] Tests written for all new code
* [x] Linter has been satisfied
* [x] Sign-off given on the changes (see CONTRIBUTING.md)

### CODE REVIEW

File: src/MatrixClient.ts [hunk 1]
```diff
@@ -721,6 +721,11 @@ export class MatrixClient extends EventEmitter {
                     await Promise.resolve(this.storage.setSyncToken(token));
                 }
             } catch (e) {
+                // If we've requested to stop syncing, don't bother checking the error.
+                if (this.stopSyncing) {
+                    LogService.info("MatrixClientLite", "Client stop requested - cancelling sync");
+                    return;
+                }
                 LogService.error("MatrixClientLite", "Error handling sync " + extractRequestError(e));
```
Comment (turt2live) [inline src/MatrixClient.ts:729]:
```suggestion

                LogService.error("MatrixClientLite", "Error handling sync " + extractRequestError(e));
```

**Review by turt2live — APPROVED** [review]
